//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameHubManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameHubManager.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Another Item.
        /// </summary>
        public static string AddAnotherItem {
            get {
                return ResourceManager.GetString("AddAnotherItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Device.
        /// </summary>
        public static string addNewDevice {
            get {
                return ResourceManager.GetString("addNewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Device Type.
        /// </summary>
        public static string addNewDeviceType {
            get {
                return ResourceManager.GetString("addNewDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Item.
        /// </summary>
        public static string addNewItem {
            get {
                return ResourceManager.GetString("addNewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Price.
        /// </summary>
        public static string addNewPrice {
            get {
                return ResourceManager.GetString("addNewPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string adminDashboard {
            get {
                return ResourceManager.GetString("adminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due.
        /// </summary>
        public static string AmountDue {
            get {
                return ResourceManager.GetString("AmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount due for each device:.
        /// </summary>
        public static string amountDueForEachDevice {
            get {
                return ResourceManager.GetString("amountDueForEachDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Due Per Device.
        /// </summary>
        public static string AmountDuePerDevice {
            get {
                return ResourceManager.GetString("AmountDuePerDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount paid for all devices:.
        /// </summary>
        public static string amountPaidForAllDevices {
            get {
                return ResourceManager.GetString("amountPaidForAllDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount paid for each device:.
        /// </summary>
        public static string amountPaidForEachDevice {
            get {
                return ResourceManager.GetString("amountPaidForEachDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to be refunded:.
        /// </summary>
        public static string amountToBeRefunded {
            get {
                return ResourceManager.GetString("amountToBeRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to be refunded for all devices:.
        /// </summary>
        public static string amountToBeRefundedForAllDevices {
            get {
                return ResourceManager.GetString("amountToBeRefundedForAllDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to be refunded per device:.
        /// </summary>
        public static string amountToBeRefundedPerDevice {
            get {
                return ResourceManager.GetString("amountToBeRefundedPerDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this device?.
        /// </summary>
        public static string areYouSureYouWantToDeleteThisDevice {
            get {
                return ResourceManager.GetString("areYouSureYouWantToDeleteThisDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio was not played because:.
        /// </summary>
        public static string audioNotPlayedReason {
            get {
                return ResourceManager.GetString("audioNotPlayedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Devices:.
        /// </summary>
        public static string availableDevices {
            get {
                return ResourceManager.GetString("availableDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Quantity:.
        /// </summary>
        public static string AvailableQuantity {
            get {
                return ResourceManager.GetString("AvailableQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home Screen.
        /// </summary>
        public static string backToHomeScreen {
            get {
                return ResourceManager.GetString("backToHomeScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biscuits.
        /// </summary>
        public static string biscuits {
            get {
                return ResourceManager.GetString("biscuits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        public static string chooseCategory {
            get {
                return ResourceManager.GetString("chooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Device Type.
        /// </summary>
        public static string chooseDeviceType {
            get {
                return ResourceManager.GetString("chooseDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Reservation.
        /// </summary>
        public static string closeReservation {
            get {
                return ResourceManager.GetString("closeReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cold Drinks.
        /// </summary>
        public static string coldDrinks {
            get {
                return ResourceManager.GetString("coldDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Scheme.
        /// </summary>
        public static string colorScheme {
            get {
                return ResourceManager.GetString("colorScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the reservation now.
        /// </summary>
        public static string completeReservationNow {
            get {
                return ResourceManager.GetString("completeReservationNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Close.
        /// </summary>
        public static string ConfirmClose {
            get {
                return ResourceManager.GetString("ConfirmClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Group Reservation.
        /// </summary>
        public static string ConfirmGroupReservation {
            get {
                return ResourceManager.GetString("ConfirmGroupReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Reservation.
        /// </summary>
        public static string ConfirmReservation {
            get {
                return ResourceManager.GetString("ConfirmReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Sale.
        /// </summary>
        public static string ConfirmSale {
            get {
                return ResourceManager.GetString("ConfirmSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does it contain controllers?.
        /// </summary>
        public static string containsControllers {
            get {
                return ResourceManager.GetString("containsControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controllers.
        /// </summary>
        public static string controllers {
            get {
                return ResourceManager.GetString("controllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2025 Zaki Malla. All rights reserved. Unauthorized use or distribution is prohibited..
        /// </summary>
        public static string copyrightNotice {
            get {
                return ResourceManager.GetString("copyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Quantity.
        /// </summary>
        public static string currentQuantity {
            get {
                return ResourceManager.GetString("currentQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customize.
        /// </summary>
        public static string customize {
            get {
                return ResourceManager.GetString("customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string dashboard {
            get {
                return ResourceManager.GetString("dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this type?.
        /// </summary>
        public static string deleteDeviceTypeConfirmation {
            get {
                return ResourceManager.GetString("deleteDeviceTypeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device List.
        /// </summary>
        public static string deviceList {
            get {
                return ResourceManager.GetString("deviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Price List.
        /// </summary>
        public static string devicePriceList {
            get {
                return ResourceManager.GetString("devicePriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device reservation has ended:.
        /// </summary>
        public static string deviceReservationEnded {
            get {
                return ResourceManager.GetString("deviceReservationEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string devices {
            get {
                return ResourceManager.GetString("devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        public static string deviceType {
            get {
                return ResourceManager.GetString("deviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type List.
        /// </summary>
        public static string deviceTypeList {
            get {
                return ResourceManager.GetString("deviceTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type Name.
        /// </summary>
        public static string deviceTypeName {
            get {
                return ResourceManager.GetString("deviceTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Types.
        /// </summary>
        public static string deviceTypes {
            get {
                return ResourceManager.GetString("deviceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device.
        /// </summary>
        public static string editDevice {
            get {
                return ResourceManager.GetString("editDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Device Type.
        /// </summary>
        public static string editDeviceType {
            get {
                return ResourceManager.GetString("editDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Price.
        /// </summary>
        public static string editPrice {
            get {
                return ResourceManager.GetString("editPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string endTime {
            get {
                return ResourceManager.GetString("endTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while closing the reservation..
        /// </summary>
        public static string errorClosingReservation {
            get {
                return ResourceManager.GetString("errorClosingReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while completing the reservation..
        /// </summary>
        public static string errorCompletingReservation {
            get {
                return ResourceManager.GetString("errorCompletingReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while connecting to the server..
        /// </summary>
        public static string errorConnectingToServer {
            get {
                return ResourceManager.GetString("errorConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the sale!.
        /// </summary>
        public static string errorDuringSale {
            get {
                return ResourceManager.GetString("errorDuringSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a price greater than 0.
        /// </summary>
        public static string errorPriceMessage {
            get {
                return ResourceManager.GetString("errorPriceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter a quantity greater than 0.
        /// </summary>
        public static string errorQuantityMessage {
            get {
                return ResourceManager.GetString("errorQuantityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore different styles according to your preferences.
        /// </summary>
        public static string exploreStyles {
            get {
                return ResourceManager.GetString("exploreStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Hour Price.
        /// </summary>
        public static string gameHourPrice {
            get {
                return ResourceManager.GetString("gameHourPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Reservation for PCs.
        /// </summary>
        public static string groupReservationForPCs {
            get {
                return ResourceManager.GetString("groupReservationForPCs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Drinks.
        /// </summary>
        public static string hotDrinks {
            get {
                return ResourceManager.GetString("hotDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Rate.
        /// </summary>
        public static string hourlyRate {
            get {
                return ResourceManager.GetString("hourlyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate for the device:.
        /// </summary>
        public static string hourlyRateForDevice {
            get {
                return ResourceManager.GetString("hourlyRateForDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly rate not set.
        /// </summary>
        public static string hourlyRateNotSet {
            get {
                return ResourceManager.GetString("hourlyRateNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indomi.
        /// </summary>
        public static string indomi {
            get {
                return ResourceManager.GetString("indomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the reservation open?.
        /// </summary>
        public static string IsReservationOpen {
            get {
                return ResourceManager.GetString("IsReservationOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lira.
        /// </summary>
        public static string lira {
            get {
                return ResourceManager.GetString("lira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to access your dashboard..
        /// </summary>
        public static string loginAccessDashboard {
            get {
                return ResourceManager.GetString("loginAccessDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with email.
        /// </summary>
        public static string loginWithEmail {
            get {
                return ResourceManager.GetString("loginWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logOut {
            get {
                return ResourceManager.GetString("logOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Menu Item Types.
        /// </summary>
        public static string manageMenuItemTypes {
            get {
                return ResourceManager.GetString("manageMenuItemTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meal Name.
        /// </summary>
        public static string mealName {
            get {
                return ResourceManager.GetString("mealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string minute {
            get {
                return ResourceManager.GetString("minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one device..
        /// </summary>
        public static string mustSelectAtLeastOneDevice {
            get {
                return ResourceManager.GetString("mustSelectAtLeastOneDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the quantity to be added.
        /// </summary>
        public static string newQuantity {
            get {
                return ResourceManager.GetString("newQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Available Devices.
        /// </summary>
        public static string NoAvailableDevices {
            get {
                return ResourceManager.GetString("NoAvailableDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Controllers.
        /// </summary>
        public static string noControllers {
            get {
                return ResourceManager.GetString("noControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices are currently available..
        /// </summary>
        public static string noDevicesAvailable {
            get {
                return ResourceManager.GetString("noDevicesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Specified Yet.
        /// </summary>
        public static string notSpecifiedYet {
            get {
                return ResourceManager.GetString("notSpecifiedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No types registered.
        /// </summary>
        public static string noTypesRegistered {
            get {
                return ResourceManager.GetString("noTypesRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Available Devices:.
        /// </summary>
        public static string NumberOfAvailableDevices {
            get {
                return ResourceManager.GetString("NumberOfAvailableDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Controllers.
        /// </summary>
        public static string NumberOfControllers {
            get {
                return ResourceManager.GetString("NumberOfControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of devices:.
        /// </summary>
        public static string numberOfDevices {
            get {
                return ResourceManager.GetString("numberOfDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of minutes played so far:.
        /// </summary>
        public static string numberOfMinutesPlayedSoFar {
            get {
                return ResourceManager.GetString("numberOfMinutesPlayedSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of minutes reserved:.
        /// </summary>
        public static string numberOfMinutesReserved {
            get {
                return ResourceManager.GetString("numberOfMinutesReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Minutes Used:.
        /// </summary>
        public static string NumberOfMinutesUsed {
            get {
                return ResourceManager.GetString("NumberOfMinutesUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Play Minutes.
        /// </summary>
        public static string NumberOfPlayMinutes {
            get {
                return ResourceManager.GetString("NumberOfPlayMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Selected Controllers:.
        /// </summary>
        public static string NumberOfSelectedControllers {
            get {
                return ResourceManager.GetString("NumberOfSelectedControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Units.
        /// </summary>
        public static string NumberOfUnits {
            get {
                return ResourceManager.GetString("NumberOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Reservation.
        /// </summary>
        public static string openReservation {
            get {
                return ResourceManager.GetString("openReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed!.
        /// </summary>
        public static string operationFailed {
            get {
                return ResourceManager.GetString("operationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was successful!.
        /// </summary>
        public static string operationSuccessful {
            get {
                return ResourceManager.GetString("operationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Hour.
        /// </summary>
        public static string perHour {
            get {
                return ResourceManager.GetString("perHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid amount for the payment..
        /// </summary>
        public static string pleaseEnterValidPaymentAmount {
            get {
                return ResourceManager.GetString("pleaseEnterValidPaymentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List of Device Types.
        /// </summary>
        public static string priceListOfDeviceTypes {
            get {
                return ResourceManager.GetString("priceListOfDeviceTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price per Unit:.
        /// </summary>
        public static string PricePerUnit {
            get {
                return ResourceManager.GetString("PricePerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity After Addition.
        /// </summary>
        public static string quantityAfterAddition {
            get {
                return ResourceManager.GetString("quantityAfterAddition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Time:.
        /// </summary>
        public static string remainingTime {
            get {
                return ResourceManager.GetString("remainingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew Quantity.
        /// </summary>
        public static string renewQuantity {
            get {
                return ResourceManager.GetString("renewQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation is open.
        /// </summary>
        public static string reservationIsOpen {
            get {
                return ResourceManager.GetString("reservationIsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Device.
        /// </summary>
        public static string ReserveDevice {
            get {
                return ResourceManager.GetString("ReserveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserve Now.
        /// </summary>
        public static string reserveNow {
            get {
                return ResourceManager.GetString("reserveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to default.
        /// </summary>
        public static string resetToDefault {
            get {
                return ResourceManager.GetString("resetToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale completed successfully!.
        /// </summary>
        public static string saleCompletedSuccessfully {
            get {
                return ResourceManager.GetString("saleCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the available devices (unreserved PCs):.
        /// </summary>
        public static string SelectAvailableDevices {
            get {
                return ResourceManager.GetString("SelectAvailableDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected reservation details:.
        /// </summary>
        public static string selectedReservationDetails {
            get {
                return ResourceManager.GetString("selectedReservationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Group Reservation.
        /// </summary>
        public static string selectGroupReservation {
            get {
                return ResourceManager.GetString("selectGroupReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item.
        /// </summary>
        public static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Multiple Items.
        /// </summary>
        public static string SellMultipleItems {
            get {
                return ResourceManager.GetString("SellMultipleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell New Item from Fridge.
        /// </summary>
        public static string sellNewItemFromFridge {
            get {
                return ResourceManager.GetString("sellNewItemFromFridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the play price before making a reservation..
        /// </summary>
        public static string setPlayPriceFirst {
            get {
                return ResourceManager.GetString("setPlayPriceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the price.
        /// </summary>
        public static string setThePrice {
            get {
                return ResourceManager.GetString("setThePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time:.
        /// </summary>
        public static string startTime {
            get {
                return ResourceManager.GetString("startTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme Customizer.
        /// </summary>
        public static string themeCustomizer {
            get {
                return ResourceManager.GetString("themeCustomizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There Are Controllers.
        /// </summary>
        public static string thereAreControllers {
            get {
                return ResourceManager.GetString("thereAreControllers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount Due for All Devices.
        /// </summary>
        public static string TotalAmountDueForAllDevices {
            get {
                return ResourceManager.GetString("TotalAmountDueForAllDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount for all devices:.
        /// </summary>
        public static string totalAmountForAllDevices {
            get {
                return ResourceManager.GetString("totalAmountForAllDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Price.
        /// </summary>
        public static string updatePrice {
            get {
                return ResourceManager.GetString("updatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string uploadImage {
            get {
                return ResourceManager.GetString("uploadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Group Reservations.
        /// </summary>
        public static string viewGroupReservations {
            get {
                return ResourceManager.GetString("viewGroupReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back! 🎉😊.
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
